<a href="https://colab.research.google.com/github/spandana1320/B19_1320/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
l=[10,2,4,'cse']
print(l)

[10, 2, 4, 'cse']


In [ ]:
l=[10,20,30,40]
l.append(50)
print(l)
l.pop()
print(l)
l.remove(30)

print(l)
l.reverse()
print(l)
l.insert(2,100)
print(l)
l.sort()
print(l)
print(sum(l))
print(l)
print(min(l))
print(l)
print(max(l))
print(l)


[10, 20, 30, 40, 50]
[10, 20, 30, 40]
[10, 20, 40]
[40, 20, 10]
[40, 20, 100, 10]
[10, 20, 40, 100]
170
[10, 20, 40, 100]
10
[10, 20, 40, 100]
100
[10, 20, 40, 100]


In [ ]:
l=[10,2,4,'cse']
for i in l:
  print(type(i),i)
  print(type(l),i)
print(l)

<class 'int'> 10
<class 'list'> 10
<class 'int'> 2
<class 'list'> 2
<class 'int'> 4
<class 'list'> 4
<class 'str'> cse
<class 'list'> cse
[10, 2, 4, 'cse']


In [ ]:
l=[10,2,4,'cse']
if 2 in l:
  print("found")
else:
    print("not found")
print(l)


found
[10, 2, 4, 'cse']


In [ ]:
s=[[10,20],[20,30],[40,20],[10,20]]
print(s)


[[10, 20], [20, 30], [40, 20], [10, 20]]


In [ ]:
l=[x**2 for x in range(6)]
print(l)

[0, 1, 4, 9, 16, 25]


In [ ]:
l=[x*2 for x in range(6)]
print(l)

[0, 2, 4, 6, 8, 10]


In [ ]:
t=(10,20,30,40,50)
print(t)
t=(10,20,30,'cse')
for i in t:
  print(type(i),i)

if 'cse' in t:
  print("f")
else:
  print("nf")



(10, 20, 30, 40, 50)
<class 'int'> 10
<class 'int'> 20
<class 'int'> 30
<class 'str'> cse
f


In [ ]:
t=(10,20,30,40,50,20,50,30)
print(t.count(20))
print(t.index(20))

2
1


In [ ]:
l=[10,20,30,40]
my_tuple=tuple(l)
print(my_tuple)

s=((10,20),(100,50))
print(s)

(10, 20, 30, 40)
((10, 20), (100, 50))


In [ ]:
s={'name':'python','id':101,'branch':'cse'}
print(s.keys())
print(s.values())
print(s.items())

for key,value in s.items():
  print(key,":",value)

s["college"]='sru'
print(s)

s['branch']='AIML'
del s['id']
print(s)

s={"101":{'name':'python','id':20,'branch':'cse'},"102":{'name':'java','id':30,'branch':'AIML'}}
print(s["102"]["name"])

dict_keys(['name', 'id', 'branch'])
dict_values(['python', 101, 'cse'])
dict_items([('name', 'python'), ('id', 101), ('branch', 'cse')])
name : python
id : 101
branch : cse
{'name': 'python', 'id': 101, 'branch': 'cse', 'college': 'sru'}
{'name': 'python', 'branch': 'AIML', 'college': 'sru'}
java


In [ ]:
print("10\t20\n30\t40")

10	20
30	40


In [ ]:
l=[[10,20],[40,50],[60,70]]
for i in l:
  print(*i)

10 20
40 50
60 70


In [ ]:
l=[[10,20],[40,50],[60,70]]
for i in l:
  print(i)

[10, 20]
[40, 50]
[60, 70]


In [ ]:
s={1,2,3,4}
print(s)
s={1,2,3,4,2,3,8,5,3,2,1}
print(s)
for i in s:
  print(i)
if 10 in s:
  print("f")
else:
  print("nf")

{1, 2, 3, 4}
{1, 2, 3, 4, 5, 8}
1
2
3
4
5
8
nf


In [ ]:
a={1,2,3,4}
b={3,4,5,6}
print(a.union(b))
print(a.intersection(b))
print(a.difference(b))
print(b.difference(a))

{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2}
{5, 6}


In [ ]:
a={1,2,3,4}
b={3,4,5,6}
print(a.symmetric_difference(b))

{1, 2, 5, 6}


In [ ]:
a={1,2,3,4}
b={3,4,5,6}
print(a.union(b))
print(a.intersection(b))
print(a.difference(b))
print(b.difference(a))
print("union",a|b)
print("intersection",a&b)
print("difference",a-b)
print("difference",b-a)
print(a.symmetric_difference(b))
print(a^b)

{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2}
{5, 6}
union {1, 2, 3, 4, 5, 6}
intersection {3, 4}
difference {1, 2}
difference {5, 6}
{1, 2, 5, 6}
{1, 2, 5, 6}


In [ ]:
s={1,2,3}
s.add(4)
print(s)
s.remove(4)
print(s)
s.clear()
print(s)

{1, 2, 3, 4}
{1, 2, 3}
set()


In [ ]:
import numpy as np
students=np.array([[80,75,21],[90,55,22],[75,45,75],[50,90,55],[25,89,56]])
print(students)
print(np.mean(students))
print(np.max(students))
print(np.min(students))
print("marks of student 3:",students[2])
print("marks of student 2 to 4",students[1:4])





[[80 75 21]
 [90 55 22]
 [75 45 75]
 [50 90 55]
 [25 89 56]]
60.2
90
21
marks of student 3: [75 45 75]
marks of student 2 to 4 [[90 55 22]
 [75 45 75]
 [50 90 55]]


In [ ]:
import numpy as np
marks = np.array([[85, 78, 92], [70, 65, 80],  [90, 88, 94],  [60, 75, 70],  [95, 85, 99] ])
avg_marks = np.mean(marks)
min_marks = np.min(marks)
max_marks = np.max(marks)
print(avg_marks)
print(min_marks)
print(max_marks)

print("Marks of Student 3:", marks[2])
print("Marks of Students 2 to 4: ", marks[1:4])

excellent= marks >80
print(excellent)

each_subject = marks.T
print("EACH SUBJECT MARKS", each_subject)

81.73333333333333
60
99
Marks of Student 3: [90 88 94]
Marks of Students 2 to 4:  [[70 65 80]
 [90 88 94]
 [60 75 70]]
[[ True False  True]
 [False False False]
 [ True  True  True]
 [False False False]
 [ True  True  True]]
EACH SUBJECT MARKS [[85 70 90 60 95]
 [78 65 88 75 85]
 [92 80 94 70 99]]
