<a href="https://colab.research.google.com/github/spandana1320/B19_1320/blob/main/LAB_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
fp=open("example.txt",'w')
fp.write("hello ! im spandana\n")
fp.write("this is file hanlding in python\n")
fp.write("python\n")
fp.close()

In [26]:
fp=open("example.txt",'r')
information=fp.read()
print("information: ",information)
fp.close()

information:  hello ! im spandana
this is file hanlding in python
python



In [27]:
fp=open("example.txt",'r')
line1=fp.readline()
print("line1: ",line1)
line2=fp.readline()
print("line2: ",line2)
line3=fp.readline()
print("line3: ",line3)
fp.close()

line1:  hello ! im spandana

line2:  this is file hanlding in python

line3:  python



In [28]:
fp=open("example.txt",'r')
lines=fp.readlines()
print("lines: ",lines)
fp.close()

lines:  ['hello ! im spandana\n', 'this is file hanlding in python\n', 'python\n']


In [29]:
fp=open("example.txt",'a')
fp.write("appending new data...\n")
fp.close()

In [30]:
fp=open("example.txt",'r')
information=fp.read()
print("information: ",information)
fp.close()

information:  hello ! im spandana
this is file hanlding in python
python
appending new data...



In [31]:
with open("example.txt",'r') as fp:
  fp=fp.read()
  print(fp)

hello ! im spandana
this is file hanlding in python
python
appending new data...



In [33]:
with open('data.csv','w',newline='') as fp:
  import csv
  writer=csv.writer(fp)
  writer.writerow(["name","marks"])
  writer.writerow(["akki","100"])
  writer.writerow(["spandy","99"])
  writer.writerow(["praneeth","98"])
  writer.writerow(["manmith","96"])






In [37]:
with open("data.csv",'r')as fp:
  read=csv.reader(fp)
  for row in read:
    print(row)

['name', 'age', 'course']
['spandy', '19', 'CSE']
['sony', '20', 'CSN']
['harshit', '21', 'ECE']


In [36]:
with open('student.csv','w',newline='') as fp:
  import csv
  wr=csv.writer(fp)
  wr.writerows([["name","age","course"],["spandy",19,'CSE'],['sony',20,"CSN"],['harshit',21,"ECE"]])


In [41]:
import numpy as np
a1=np.array([1,2,3,4])
print("1D array:",a1)
a2=np.array([[1,2,3,4],[5,6,7,8]])
print("2D array:",a2)
zeros_arr=np.zeros((3,3))
print("zeros array:",zeros_arr)
ones_arr=np.ones((3,3))
print("ones array:",ones_arr)
range_arr=np.arange(10)
print("range array:",range_arr)
random_arr=np.random.random((3,3))
print("random array:",random_arr)

1D array: [1 2 3 4]
2D array: [[1 2 3 4]
 [5 6 7 8]]
zeros array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
range array: [0 1 2 3 4 5 6 7 8 9]
random array: [[0.69396353 0.02292753 0.29150241]
 [0.60212855 0.49280293 0.02727074]
 [0.22925669 0.9741776  0.07205046]]


In [42]:
#array attributes
a=np.array([[1,2,3],[4,5,6]])
print("shape of array : ",a.shape)
print("size of array : ",a.size)
print("data type of array : ",a.dtype)
print("dimension : ",a.ndim)
print("item size : ",a.itemsize)

shape of array :  (2, 3)
size of array :  6
data type of array :  int64
dimension :  2
item size :  8


In [50]:
a=np.array([10,20,30,40,50])
print("First element:",a[0])
print("Second element:",a[1])
print("Last element:",a[-1])
print("slice[1:4]",a[1:4])
print("slice[1:4]",a[1:4:2])
print("every second element",a[::2])

a2=np.array([[1,2,3],[4,5,6]])
print("element at row 1 col2",a2[1,2])
print("element at row 0 col2",a2[0,2])
print("second row",a2[1:])
print("first col",a2[:,0])
print("first row",a2[0,:])

First element: 10
Second element: 20
Last element: 50
slice[1:4] [20 30 40]
slice[1:4] [20 40]
every second element [10 30 50]
element at row 1 col2 6
element at row 0 col2 3
second row [[4 5 6]]
first col [1 4]
first row [1 2 3]


In [53]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print("a+b",a+b)
print("a-b",a-b)
print("a*b",a*b)
print("a/b",a/b)
print("a%b",a%b)
print("a**b",a**b)



a+b [ 7  9 11 13 15]
a-b [-5 -5 -5 -5 -5]
a*b [ 6 14 24 36 50]
a/b [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
a%b [1 2 3 4 5]
a**b [      1     128    6561  262144 9765625]


In [54]:
#mathematical functions
a=np.array([0,np.pi/2,np.pi])
print("sine",np.sin(a))
print("cosine",np.cos(a))
print("sqaure root",np.sqrt([1,4,9]))
print("exponential",np.exp([1,2]))


sine [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cosine [ 1.000000e+00  6.123234e-17 -1.000000e+00]
sqaure root [1. 2. 3.]
exponential [2.71828183 7.3890561 ]


In [59]:
#aggregate Functions
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Sum:",np.sum(arr))
print("Min:",np.min(arr))
print("Max:",np.max(arr))
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Standard Deviation:",np.std(arr))
print("Sum along axis 0:",np.sum(arr,axis=0)) #column wise sum
print("Sum along axis 1:",np.sum(arr,axis=1)) #row wise sum

Array:
 [[1 2 3]
 [4 5 6]]
Sum: 21
Min: 1
Max: 6
Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Sum along axis 0: [5 7 9]
Sum along axis 1: [ 6 15]


In [63]:

#Broadcasting
# it allows operationson arrays of different shapes
a=np.array([1,2,3])
b=5
print("Add scalar to array:",a+b)
c=np.array([[1],[2],[3]])
d=np.array([4,5,6])
print("Broadcasted sum\n:",c+d)


Add scalar to array: [6 7 8]
Broadcasted sum
: [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [64]:
#Matrix Operations
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n",np.dot(A,B))
print("Matrix Transpose:\n",A.T)
print("Matrix Inverse:\n",np.linalg.inv(A))
print("Matrix Determinant:\n",np.linalg.det(A))

Matrix Multiplication:
 [[19 22]
 [43 50]]
Matrix Transpose:
 [[1 3]
 [2 4]]
Matrix Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matrix Determinant:
 -2.0000000000000004


In [65]:
#Sample Program - Student Analsis
import numpy as np
# Marks of students in 3 subjects
marks = np.array([
[85, 90, 88],
[78, 81, 85],
[92, 89, 95]
])
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
